# Generated by Django 4.1.2 on 2022-10-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date_and_time',
        ),
    ]
