# Generated by Django 4.1.2 on 2022-10-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='name_neighbourhood',
            new_name='neighbourhood',
        ),
    ]
