# Generated by Django 4.1.2 on 2022-10-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leader',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='resident',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='gender',
        ),
    ]
