# Generated by Django 4.1.2 on 2022-10-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paza', '0002_rename_name_neighbourhood_notifications_neighbourhood'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
