# Generated by Django 4.1.2 on 2022-10-29 11:40

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paza', '0005_newpost_rename_time_date_comment_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='description',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='time_date',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='tittle',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='video',
        ),
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paza.resident'),
        ),
        migrations.AddField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='image_caption',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='image_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
