# Generated by Django 4.1.2 on 2022-11-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paza', '0006_remove_posts_description_remove_posts_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='place',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='time_date',
        ),
        migrations.AddField(
            model_name='forum',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='name',
            field=models.CharField(default='anonymous', max_length=200),
        ),
        migrations.AddField(
            model_name='forum',
            name='topic',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
